### ISSUE TITLE
Kubernetes Helm Chart?

### ISSUE THREAD

**Issue by bbodenmiller** [OneBusAway/docker#12]
Might also be worth having.

**Comment by barbeau** [comment]
@bbodenmiller Could you please explain a bit more?

**Comment by bbodenmiller** [comment]
OneBusAway's backend services likely should not be run in just one Docker container but rather a number with each serving it's own purpose, to enable scaling, etc. For that you need a container orchestrater like Kubernetes. Kubernetes Helm Charts are a way to ship ready to use Kubernetes orchestrations (collections of Docker images & more)... A package manager of sorts.

https://github.com/kubernetes/helm/blob/master/README.md

https://helm.sh/

**Comment by danp** [comment]
I think this could be useful someday but there's still much to figure out with the OBA docker image, such as configuration, volume expectations, ports, etc. But shouldn't be anything stopping folks from experimenting!

**Comment by gelinger777** [comment]
is a good idea. but @danp  is right. Still docker  repo is very  new. I could help with Kubernetes  when time comes.
