### ISSUE TITLE
How to get the docker package

### ISSUE THREAD

**Issue by brodyFlannigan** [OneBusAway/docker#16]
Hey folks,
I want to run OBA v.2 via Docker (I'm running the debian program on Windows 10) but I don't understand how to get the actual files from GitHub and into my system.
Any help would be appreciated (I think this calls for improvements to the documentation)

Thanks ahead of time!

**Comment by barbeau** [comment]
@dudebrains01 You can download the GitHub repository as a zip file or "clone" it - see https://help.github.com/en/github/creating-cloning-and-archiving-repositories/cloning-a-repository.
