### ISSUE TITLE
On docker 20.10 build failed error on docker build-bundle

### ISSUE THREAD

**Issue by changtung** [OneBusAway/docker#23]
I run according to readme: 
`docker-compose up -d build-bundle`
i receive error: 
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project onebusaway-core: Fatal error compiling: invalid flag: --release -> [Help 1]`
`ERROR: Service 'build-bundle' failed to build : Build failed`

**Comment by aaronbrethorst** [comment]
this is now fixed in `feature/oba-2x`
