### ISSUE TITLE
Get onebusaway-api-webapp working with /bundle

### ISSUE THREAD

**Issue by danp** [OneBusAway/docker#3]
Building on #2, add onebusaway-api-webapp using the bundle directory at `/bundle`. It should successfully respond to an http request to `/onebusaway-api-webapp/api/where/config.json?key=TEST` or similar.

**Comment by barbeau** [comment]
For transitioning to MySQL or Postgres - @scrudden said on Slack (https://onebusaway.slack.com/archives/C8USPA8V6/p1516992123000409) that he's set up TheTransitClock w/ Postgres on Docker:
https://github.com/TheTransitClock/transitclockDocker/tree/prediction_comparison_hart

>This is done with go.sh but it could also be done with docker compose.
>
>all you do is type ./go.sh

**Comment by barbeau** [comment]
We can also follow OBA-specific database config instructions at:
https://github.com/OneBusAway/onebusaway-application-modules/wiki/Database-Guide#datasource

And specific to Postgres:
https://github.com/OneBusAway/onebusaway-application-modules/wiki/Database-Guide#postgresql

**Comment by danp** [comment]
Ended up changing this up to use postgres in #5.
