### ISSUE TITLE
Proposal: Start pre-built docker images

### ISSUE THREAD

**Issue by Neo2308** [OneBusAway/docker#41]
Can we start releasing pre-built docker images so that users do not have to checkout the code and build their own docker images?

Since the image is now picking the zip file dynamically (and it isn't baked into the docker image itself), we could potentially deploy the app in k8s just using a file similar to [oba.yaml](https://github.com/OneBusAway/onebusaway-docker/blob/main/oba.yaml) simplifying usage.

**Comment by Yalab7** [comment]
I think this would be a great enhancement to the deployment process, but shouldn't only the maintainers have creation/push access to the repository containing the pre-built docker image?

**Comment by aaronbrethorst** [comment]
Thanks for opening this issue, @Neo2308. It's on my TODO list.
