### ISSUE TITLE
GitHub Action to automatically tag and publish new builds to Docker on merge to main

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/docker#43]
The GitHub Action CI config should be changed to automatically tag and publish our Docker images to Docker Hub on successful merge to main. I'll need to work with whomever picks this up to add the necessary secret token to this repo's settings.

**Comment by Altonhe** [comment]
I can handle this, could you assign it to me?

**Comment by aaronbrethorst** [comment]
thank you @Altonhe! assigned.

**Comment by aaronbrethorst** [comment]
Fixed in #46 - thanks Alton!
