### ISSUE TITLE
Add support for PostgreSQL 

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/docker#50]
Let's make it possible to use the PostgreSQL database in addition to MySQL. MySQL should remain the default.

Here's what I know should change:

1. Allow the specification of the JDBC driver class in data-sources.xml
2. Add the PostgreSQL JDBC driver to the app server docker image (https://jdbc.postgresql.org)
3. Update the README with information on using PG instead of MySQL

I'm sure I'm forgetting something here, so use your best judgment on getting this built out!

**Comment by CesarAndrade007** [comment]
I'd like to take this on @aaronbrethorst!

**Comment by aaronbrethorst** [comment]
Any chance you might have the bandwidth to tackle this, @Altonhe?

**Comment by Altonhe** [comment]
@aaronbrethorst no problem

**Comment by Altonhe** [comment]
Blocked by https://github.com/OneBusAway/onebusaway-application-modules/issues/352

**Comment by Neo2308** [comment]
@Altonhe this should be unblocked now.

**Comment by aaronbrethorst** [comment]
It’s not unblocked yet. We need to start building our own OBA JAR and WAR files first
