### ISSUE TITLE
Create guidance on deploying with Kubernetes

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/docker#54]
It isn't clear to me at this time whether this should depend on the outcome of #62 or if this should be a standalone solution. Whoever ends up working on this will need to make that determination.

The end result of this should be a guide written in Markdown that a reasonably technical person, but not necessarily a software developer (think senior IT at a transit agency) can use to deploy OneBusAway in a scalable, secure way with Kubernetes. Note that there are already some Kubernetes resources in this repo to be built on top of.

Despite the fact that this task appears in the onebusaway-docker issue tracker, the end product should be added to https://github.com/oneBusAway/onebusaway-docs

Look at the guides published on https://developer.onebusaway.org, like this [Quickstart guide](https://developer.onebusaway.org/guides/quickstart-guide) for a sense of tone, length, etc.

**Comment by imlakshay08** [comment]
Hey @aaronbrethorst , I would like to work on this one. Could you please assign this to me?

**Comment by AyeshaLoladia** [comment]
HII @aaronbrethorst , I would like to work on this issue. Can you please assign it to me. Thank you

**Comment by aaronbrethorst** [comment]
complete!
