### ISSUE TITLE
Push tagged builds to Docker Hub

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/docker#60]
Right now, our GitHub Actions workflow pushes two tags for each Docker image we publish up to Docker Hub:

* `IMAGE_NAME:latest` (e.g. `opentransitsoftwarefoundation/onebusaway-api-webapp:latest`)
* `IMAGE_NAME:GIT-SHA-VALUE` (e.g. `opentransitsoftwarefoundation/onebusaway-api-webapp:624585353e8c91cf7be3ba2c4ad7f8e07d5082f4`)

this is great, but it would also be great to be able to push up tagged releases.

here's my desired workflow:

1. I go to https://github.com/OneBusAway/onebusaway-docker/releases/new
2. Create a tag (e.g. `2.4.18-cs-v1.0.0`), add release notes, and click Publish Release
3. the GitHub Actions workflow creates a new set of tagged releases on Docker Hub (e.g. `opentransitsoftwarefoundation/onebusaway-api-webapp:2.4.18-cs-v1.0.0`)

**Comment by Altonhe** [comment]
I'd like to try on this, could you assign it to me?

**Comment by aaronbrethorst** [comment]
heck yes, thank you @Altonhe

**Comment by aaronbrethorst** [comment]
fixed in #61
