### ISSUE TITLE
Deployment Strategies: Evaluate Terraform, Pulumi, etc and create IaC artifacts for cloud deployments

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/docker#62]
Instead of implementing cloud-specific resources for deployment (e.g. CloudFormation templates for AWS, Azure Resource Manager for Azure, etc.), we should probably use a tool like Terraform or Pulumi that can help us abstract away the cloud-specific aspects of the deployment. We need an evaluation of the market, and a determination of which tools might be suitable. 

Then, there should be a 'bake-off': each tool should be put through its paces and a determination made as to which tool we should use.

Finally we will create the necessary IaC artifacts for deploying an OBA server with the selected tool.

Update: with rumors floating around that IBM is going to acquire Hashicorp, I'd like to also evaluate OpenTofu, which is a Terraform fork: https://opentofu.org

Update 2: IBM acquired Hashicorp, and now Oracle is throwing its weight behind OpenTofu. https://news.ycombinator.com/item?id=40365198

**Comment by MeenuyD** [comment]
Hello @aaronbrethorst Sir,
I believe leveraging an Infrastructure as Code (IaC) tool is an excellent idea for deploying OneBusAway. After considering factors such as ease of use, code readability, cloud provider support, and state management, Terraform stands out as the optimal choice. Its declarative configuration, multi-cloud compatibility, and robust state management capabilities align perfectly with our requirements.

**Comment by aaronbrethorst** [comment]
complete!
