### ISSUE TITLE
Improve user experience when opening a bash terminal in the app container

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/docker#79]
right now, running `docker run -it --entrypoint /bin/bash oba_app` will leave you in the empty `/oba/webapps/` subdirectory for the acta web app. This is undesirable. Instead, we should:

- [ ] Delete the `/oba/webapps` directory upon container configuration.
- [ ] Set the user's default directory to be either `/oba` or `/usr/local/tomcat`. I'm not sure which and could be persuaded either way.

**Comment by Altonhe** [comment]
I want to work on this, could you assign it to me?
