### ISSUE TITLE
Should we support installation using helm charts?

### ISSUE THREAD

**Issue by Neo2308** [OneBusAway/docker#94]
Would it be worth creating a basic helm chart for this? It would allow folks to leverage tools like flux/argoCD.

**Comment by Neo2308** [comment]
@aaronbrethorst if you think this is worth doing, I can take this up.

Here is an example to illustrate the scope of work: https://github.com/helm/examples/tree/main

**Comment by aaronbrethorst** [comment]
@Neo2308 please join our slack so you can chat with me and @alanb2718, who is heading up our deployment work about this. https://join.slack.com/t/onebusaway/shared_invite/zt-2jve26vs6-~qXjgxv_HkTliUKhAnuSDA

**Comment by aaronbrethorst** [comment]
Sounds like the answer is yes!

**Comment by aaronbrethorst** [comment]
wrapped up in the onebusaway-deployment repo
